name: image-caption
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - cudatoolkit=11.8
  - cudnn=8.9
  - pip:
    - tensorflow[and-cuda]==2.17.*
    - pandas==2.2.*
    - numpy==1.26.*
    - matplotlib==3.9.*
    - Pillow==10.4.*
    - streamlit==1.37.*
    - nltk==3.9.*
    - scikit-learn==1.5.*
    - tqdm==4.66.*
    - jupyter==1.0.*
    - plotly==6.9.*
    - xgboost==3.2.*
    - shap==0.51.*
    - keras-tuner
